-- =============================================================================
-- SAS-to-Snowflake Migration Validation Queries
-- Schema: SAS_MIGRATION_DB.BANKING
-- =============================================================================

-- =============================================================================
-- Validation: CUST_ACCOUNTS
-- =============================================================================

-- Row Count Validation: CUST_ACCOUNTS
-- Expected source count: 1980
SELECT
    'CUST_ACCOUNTS' AS TABLE_NAME,
    COUNT(*) AS TARGET_ROW_COUNT,
    1980 AS SOURCE_ROW_COUNT,
    CASE
        WHEN COUNT(*) = 1980 THEN 'PASS'
        ELSE 'FAIL: delta=' || (COUNT(*) - 1980)::VARCHAR
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.CUST_ACCOUNTS;

-- Null Count Validation: CUST_ACCOUNTS.CUSTOMER_ID
-- Expected source null count: 0
SELECT
    'CUST_ACCOUNTS.CUSTOMER_ID' AS VALIDATION_TARGET,
    COUNT(*) - COUNT(CUSTOMER_ID) AS TARGET_NULL_COUNT,
    0 AS SOURCE_NULL_COUNT,
    CASE
        WHEN (COUNT(*) - COUNT(CUSTOMER_ID)) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.CUST_ACCOUNTS;

-- Distinct Count Validation: CUST_ACCOUNTS.CUSTOMER_ID
-- Expected source distinct count: 1000
SELECT
    'CUST_ACCOUNTS.CUSTOMER_ID' AS VALIDATION_TARGET,
    COUNT(DISTINCT CUSTOMER_ID) AS TARGET_DISTINCT,
    1000 AS SOURCE_DISTINCT,
    CASE
        WHEN COUNT(DISTINCT CUSTOMER_ID) = 1000 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.CUST_ACCOUNTS;

-- Column Sum Validation: CUST_ACCOUNTS.CUSTOMER_ID
-- Expected source sum: 2978189.0
SELECT
    'CUST_ACCOUNTS.CUSTOMER_ID' AS VALIDATION_TARGET,
    SUM(CUSTOMER_ID) AS TARGET_SUM,
    2978189.0 AS SOURCE_SUM,
    ABS(SUM(CUSTOMER_ID) - 2978189.0) AS ABSOLUTE_DIFF,
    CASE
        WHEN ABS(SUM(CUSTOMER_ID) - 2978189.0) < 0.01 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.CUST_ACCOUNTS;

-- Min/Max Validation: CUST_ACCOUNTS.CUSTOMER_ID
-- Expected: MIN=1001, MAX=2000
SELECT
    'CUST_ACCOUNTS.CUSTOMER_ID' AS VALIDATION_TARGET,
    MIN(CUSTOMER_ID) AS TARGET_MIN,
    MAX(CUSTOMER_ID) AS TARGET_MAX,
    1001 AS SOURCE_MIN,
    2000 AS SOURCE_MAX,
    CASE
        WHEN MIN(CUSTOMER_ID) = 1001
         AND MAX(CUSTOMER_ID) = 2000 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.CUST_ACCOUNTS;

-- Null Count Validation: CUST_ACCOUNTS.ACCOUNT_ID
-- Expected source null count: 0
SELECT
    'CUST_ACCOUNTS.ACCOUNT_ID' AS VALIDATION_TARGET,
    COUNT(*) - COUNT(ACCOUNT_ID) AS TARGET_NULL_COUNT,
    0 AS SOURCE_NULL_COUNT,
    CASE
        WHEN (COUNT(*) - COUNT(ACCOUNT_ID)) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.CUST_ACCOUNTS;

-- Distinct Count Validation: CUST_ACCOUNTS.ACCOUNT_ID
-- Expected source distinct count: 1980
SELECT
    'CUST_ACCOUNTS.ACCOUNT_ID' AS VALIDATION_TARGET,
    COUNT(DISTINCT ACCOUNT_ID) AS TARGET_DISTINCT,
    1980 AS SOURCE_DISTINCT,
    CASE
        WHEN COUNT(DISTINCT ACCOUNT_ID) = 1980 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.CUST_ACCOUNTS;

-- Null Count Validation: CUST_ACCOUNTS.ACCOUNT_TYPE
-- Expected source null count: 0
SELECT
    'CUST_ACCOUNTS.ACCOUNT_TYPE' AS VALIDATION_TARGET,
    COUNT(*) - COUNT(ACCOUNT_TYPE) AS TARGET_NULL_COUNT,
    0 AS SOURCE_NULL_COUNT,
    CASE
        WHEN (COUNT(*) - COUNT(ACCOUNT_TYPE)) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.CUST_ACCOUNTS;

-- Distinct Count Validation: CUST_ACCOUNTS.ACCOUNT_TYPE
-- Expected source distinct count: 3
SELECT
    'CUST_ACCOUNTS.ACCOUNT_TYPE' AS VALIDATION_TARGET,
    COUNT(DISTINCT ACCOUNT_TYPE) AS TARGET_DISTINCT,
    3 AS SOURCE_DISTINCT,
    CASE
        WHEN COUNT(DISTINCT ACCOUNT_TYPE) = 3 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.CUST_ACCOUNTS;

-- Null Count Validation: CUST_ACCOUNTS.IS_ACTIVE
-- Expected source null count: 0
SELECT
    'CUST_ACCOUNTS.IS_ACTIVE' AS VALIDATION_TARGET,
    COUNT(*) - COUNT(IS_ACTIVE) AS TARGET_NULL_COUNT,
    0 AS SOURCE_NULL_COUNT,
    CASE
        WHEN (COUNT(*) - COUNT(IS_ACTIVE)) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.CUST_ACCOUNTS;

-- Distinct Count Validation: CUST_ACCOUNTS.IS_ACTIVE
-- Expected source distinct count: 2
SELECT
    'CUST_ACCOUNTS.IS_ACTIVE' AS VALIDATION_TARGET,
    COUNT(DISTINCT IS_ACTIVE) AS TARGET_DISTINCT,
    2 AS SOURCE_DISTINCT,
    CASE
        WHEN COUNT(DISTINCT IS_ACTIVE) = 2 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.CUST_ACCOUNTS;

-- Null Count Validation: CUST_ACCOUNTS.START_DATE
-- Expected source null count: 0
SELECT
    'CUST_ACCOUNTS.START_DATE' AS VALIDATION_TARGET,
    COUNT(*) - COUNT(START_DATE) AS TARGET_NULL_COUNT,
    0 AS SOURCE_NULL_COUNT,
    CASE
        WHEN (COUNT(*) - COUNT(START_DATE)) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.CUST_ACCOUNTS;

-- Distinct Count Validation: CUST_ACCOUNTS.START_DATE
-- Expected source distinct count: 1235
SELECT
    'CUST_ACCOUNTS.START_DATE' AS VALIDATION_TARGET,
    COUNT(DISTINCT START_DATE) AS TARGET_DISTINCT,
    1235 AS SOURCE_DISTINCT,
    CASE
        WHEN COUNT(DISTINCT START_DATE) = 1235 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.CUST_ACCOUNTS;

-- Null Count Validation: CUST_ACCOUNTS.END_DATE
-- Expected source null count: 1709
SELECT
    'CUST_ACCOUNTS.END_DATE' AS VALIDATION_TARGET,
    COUNT(*) - COUNT(END_DATE) AS TARGET_NULL_COUNT,
    1709 AS SOURCE_NULL_COUNT,
    CASE
        WHEN (COUNT(*) - COUNT(END_DATE)) = 1709 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.CUST_ACCOUNTS;

-- Distinct Count Validation: CUST_ACCOUNTS.END_DATE
-- Expected source distinct count: 257
SELECT
    'CUST_ACCOUNTS.END_DATE' AS VALIDATION_TARGET,
    COUNT(DISTINCT END_DATE) AS TARGET_DISTINCT,
    257 AS SOURCE_DISTINCT,
    CASE
        WHEN COUNT(DISTINCT END_DATE) = 257 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.CUST_ACCOUNTS;

-- Hash-based Row Validation: CUST_ACCOUNTS
-- Compares MD5 hash of concatenated columns for sample rows
SELECT
    CUSTOMER_ID, ACCOUNT_ID,
    MD5(CONCAT_WS('|', CUSTOMER_ID, ACCOUNT_ID, ACCOUNT_TYPE, IS_ACTIVE, START_DATE, END_DATE)) AS ROW_HASH
FROM SAS_MIGRATION_DB.BANKING.CUST_ACCOUNTS
ORDER BY CUSTOMER_ID, ACCOUNT_ID
LIMIT 100;

-- =============================================================================
-- Validation: DAILY_BALANCE
-- =============================================================================

-- Row Count Validation: DAILY_BALANCE
-- Expected source count: 122760
SELECT
    'DAILY_BALANCE' AS TABLE_NAME,
    COUNT(*) AS TARGET_ROW_COUNT,
    122760 AS SOURCE_ROW_COUNT,
    CASE
        WHEN COUNT(*) = 122760 THEN 'PASS'
        ELSE 'FAIL: delta=' || (COUNT(*) - 122760)::VARCHAR
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.DAILY_BALANCE;

-- Null Count Validation: DAILY_BALANCE.CUSTOMER_ID
-- Expected source null count: 0
SELECT
    'DAILY_BALANCE.CUSTOMER_ID' AS VALIDATION_TARGET,
    COUNT(*) - COUNT(CUSTOMER_ID) AS TARGET_NULL_COUNT,
    0 AS SOURCE_NULL_COUNT,
    CASE
        WHEN (COUNT(*) - COUNT(CUSTOMER_ID)) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.DAILY_BALANCE;

-- Distinct Count Validation: DAILY_BALANCE.CUSTOMER_ID
-- Expected source distinct count: 1000
SELECT
    'DAILY_BALANCE.CUSTOMER_ID' AS VALIDATION_TARGET,
    COUNT(DISTINCT CUSTOMER_ID) AS TARGET_DISTINCT,
    1000 AS SOURCE_DISTINCT,
    CASE
        WHEN COUNT(DISTINCT CUSTOMER_ID) = 1000 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.DAILY_BALANCE;

-- Column Sum Validation: DAILY_BALANCE.CUSTOMER_ID
-- Expected source sum: 184647718.0
SELECT
    'DAILY_BALANCE.CUSTOMER_ID' AS VALIDATION_TARGET,
    SUM(CUSTOMER_ID) AS TARGET_SUM,
    184647718.0 AS SOURCE_SUM,
    ABS(SUM(CUSTOMER_ID) - 184647718.0) AS ABSOLUTE_DIFF,
    CASE
        WHEN ABS(SUM(CUSTOMER_ID) - 184647718.0) < 0.01 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.DAILY_BALANCE;

-- Min/Max Validation: DAILY_BALANCE.CUSTOMER_ID
-- Expected: MIN=1001, MAX=2000
SELECT
    'DAILY_BALANCE.CUSTOMER_ID' AS VALIDATION_TARGET,
    MIN(CUSTOMER_ID) AS TARGET_MIN,
    MAX(CUSTOMER_ID) AS TARGET_MAX,
    1001 AS SOURCE_MIN,
    2000 AS SOURCE_MAX,
    CASE
        WHEN MIN(CUSTOMER_ID) = 1001
         AND MAX(CUSTOMER_ID) = 2000 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.DAILY_BALANCE;

-- Null Count Validation: DAILY_BALANCE.ACCOUNT_ID
-- Expected source null count: 0
SELECT
    'DAILY_BALANCE.ACCOUNT_ID' AS VALIDATION_TARGET,
    COUNT(*) - COUNT(ACCOUNT_ID) AS TARGET_NULL_COUNT,
    0 AS SOURCE_NULL_COUNT,
    CASE
        WHEN (COUNT(*) - COUNT(ACCOUNT_ID)) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.DAILY_BALANCE;

-- Distinct Count Validation: DAILY_BALANCE.ACCOUNT_ID
-- Expected source distinct count: 1980
SELECT
    'DAILY_BALANCE.ACCOUNT_ID' AS VALIDATION_TARGET,
    COUNT(DISTINCT ACCOUNT_ID) AS TARGET_DISTINCT,
    1980 AS SOURCE_DISTINCT,
    CASE
        WHEN COUNT(DISTINCT ACCOUNT_ID) = 1980 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.DAILY_BALANCE;

-- Null Count Validation: DAILY_BALANCE.BALANCE_DATE
-- Expected source null count: 0
SELECT
    'DAILY_BALANCE.BALANCE_DATE' AS VALIDATION_TARGET,
    COUNT(*) - COUNT(BALANCE_DATE) AS TARGET_NULL_COUNT,
    0 AS SOURCE_NULL_COUNT,
    CASE
        WHEN (COUNT(*) - COUNT(BALANCE_DATE)) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.DAILY_BALANCE;

-- Distinct Count Validation: DAILY_BALANCE.BALANCE_DATE
-- Expected source distinct count: 62
SELECT
    'DAILY_BALANCE.BALANCE_DATE' AS VALIDATION_TARGET,
    COUNT(DISTINCT BALANCE_DATE) AS TARGET_DISTINCT,
    62 AS SOURCE_DISTINCT,
    CASE
        WHEN COUNT(DISTINCT BALANCE_DATE) = 62 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.DAILY_BALANCE;

-- Null Count Validation: DAILY_BALANCE.END_OF_DAY_BALANCE
-- Expected source null count: 0
SELECT
    'DAILY_BALANCE.END_OF_DAY_BALANCE' AS VALIDATION_TARGET,
    COUNT(*) - COUNT(END_OF_DAY_BALANCE) AS TARGET_NULL_COUNT,
    0 AS SOURCE_NULL_COUNT,
    CASE
        WHEN (COUNT(*) - COUNT(END_OF_DAY_BALANCE)) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.DAILY_BALANCE;

-- Distinct Count Validation: DAILY_BALANCE.END_OF_DAY_BALANCE
-- Expected source distinct count: 108445
SELECT
    'DAILY_BALANCE.END_OF_DAY_BALANCE' AS VALIDATION_TARGET,
    COUNT(DISTINCT END_OF_DAY_BALANCE) AS TARGET_DISTINCT,
    108445 AS SOURCE_DISTINCT,
    CASE
        WHEN COUNT(DISTINCT END_OF_DAY_BALANCE) = 108445 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.DAILY_BALANCE;

-- Column Sum Validation: DAILY_BALANCE.END_OF_DAY_BALANCE
-- Expected source sum: 348911298.86
SELECT
    'DAILY_BALANCE.END_OF_DAY_BALANCE' AS VALIDATION_TARGET,
    SUM(END_OF_DAY_BALANCE) AS TARGET_SUM,
    348911298.86 AS SOURCE_SUM,
    ABS(SUM(END_OF_DAY_BALANCE) - 348911298.86) AS ABSOLUTE_DIFF,
    CASE
        WHEN ABS(SUM(END_OF_DAY_BALANCE) - 348911298.86) < 0.01 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.DAILY_BALANCE;

-- Min/Max Validation: DAILY_BALANCE.END_OF_DAY_BALANCE
-- Expected: MIN=0.00, MAX=9856.79
SELECT
    'DAILY_BALANCE.END_OF_DAY_BALANCE' AS VALIDATION_TARGET,
    MIN(END_OF_DAY_BALANCE) AS TARGET_MIN,
    MAX(END_OF_DAY_BALANCE) AS TARGET_MAX,
    0.00 AS SOURCE_MIN,
    9856.79 AS SOURCE_MAX,
    CASE
        WHEN MIN(END_OF_DAY_BALANCE) = 0.00
         AND MAX(END_OF_DAY_BALANCE) = 9856.79 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.DAILY_BALANCE;

-- Null Count Validation: DAILY_BALANCE.BALANCE_MONTH
-- Expected source null count: 0
SELECT
    'DAILY_BALANCE.BALANCE_MONTH' AS VALIDATION_TARGET,
    COUNT(*) - COUNT(BALANCE_MONTH) AS TARGET_NULL_COUNT,
    0 AS SOURCE_NULL_COUNT,
    CASE
        WHEN (COUNT(*) - COUNT(BALANCE_MONTH)) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.DAILY_BALANCE;

-- Distinct Count Validation: DAILY_BALANCE.BALANCE_MONTH
-- Expected source distinct count: 2
SELECT
    'DAILY_BALANCE.BALANCE_MONTH' AS VALIDATION_TARGET,
    COUNT(DISTINCT BALANCE_MONTH) AS TARGET_DISTINCT,
    2 AS SOURCE_DISTINCT,
    CASE
        WHEN COUNT(DISTINCT BALANCE_MONTH) = 2 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.DAILY_BALANCE;

-- Hash-based Row Validation: DAILY_BALANCE
-- Compares MD5 hash of concatenated columns for sample rows
SELECT
    CUSTOMER_ID, ACCOUNT_ID, BALANCE_DATE,
    MD5(CONCAT_WS('|', CUSTOMER_ID, ACCOUNT_ID, BALANCE_DATE, END_OF_DAY_BALANCE, BALANCE_MONTH)) AS ROW_HASH
FROM SAS_MIGRATION_DB.BANKING.DAILY_BALANCE
ORDER BY CUSTOMER_ID, ACCOUNT_ID, BALANCE_DATE
LIMIT 100;

-- =============================================================================
-- Validation: MONTHLY_AMB
-- =============================================================================

-- Row Count Validation: MONTHLY_AMB
-- Expected source count: 1980
SELECT
    'MONTHLY_AMB' AS TABLE_NAME,
    COUNT(*) AS TARGET_ROW_COUNT,
    1980 AS SOURCE_ROW_COUNT,
    CASE
        WHEN COUNT(*) = 1980 THEN 'PASS'
        ELSE 'FAIL: delta=' || (COUNT(*) - 1980)::VARCHAR
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.MONTHLY_AMB;

-- Null Count Validation: MONTHLY_AMB.CUSTOMER_ID
-- Expected source null count: 0
SELECT
    'MONTHLY_AMB.CUSTOMER_ID' AS VALIDATION_TARGET,
    COUNT(*) - COUNT(CUSTOMER_ID) AS TARGET_NULL_COUNT,
    0 AS SOURCE_NULL_COUNT,
    CASE
        WHEN (COUNT(*) - COUNT(CUSTOMER_ID)) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.MONTHLY_AMB;

-- Distinct Count Validation: MONTHLY_AMB.CUSTOMER_ID
-- Expected source distinct count: 1000
SELECT
    'MONTHLY_AMB.CUSTOMER_ID' AS VALIDATION_TARGET,
    COUNT(DISTINCT CUSTOMER_ID) AS TARGET_DISTINCT,
    1000 AS SOURCE_DISTINCT,
    CASE
        WHEN COUNT(DISTINCT CUSTOMER_ID) = 1000 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.MONTHLY_AMB;

-- Column Sum Validation: MONTHLY_AMB.CUSTOMER_ID
-- Expected source sum: 2978189.0
SELECT
    'MONTHLY_AMB.CUSTOMER_ID' AS VALIDATION_TARGET,
    SUM(CUSTOMER_ID) AS TARGET_SUM,
    2978189.0 AS SOURCE_SUM,
    ABS(SUM(CUSTOMER_ID) - 2978189.0) AS ABSOLUTE_DIFF,
    CASE
        WHEN ABS(SUM(CUSTOMER_ID) - 2978189.0) < 0.01 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.MONTHLY_AMB;

-- Min/Max Validation: MONTHLY_AMB.CUSTOMER_ID
-- Expected: MIN=1001, MAX=2000
SELECT
    'MONTHLY_AMB.CUSTOMER_ID' AS VALIDATION_TARGET,
    MIN(CUSTOMER_ID) AS TARGET_MIN,
    MAX(CUSTOMER_ID) AS TARGET_MAX,
    1001 AS SOURCE_MIN,
    2000 AS SOURCE_MAX,
    CASE
        WHEN MIN(CUSTOMER_ID) = 1001
         AND MAX(CUSTOMER_ID) = 2000 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.MONTHLY_AMB;

-- Null Count Validation: MONTHLY_AMB.ACCOUNT_ID
-- Expected source null count: 0
SELECT
    'MONTHLY_AMB.ACCOUNT_ID' AS VALIDATION_TARGET,
    COUNT(*) - COUNT(ACCOUNT_ID) AS TARGET_NULL_COUNT,
    0 AS SOURCE_NULL_COUNT,
    CASE
        WHEN (COUNT(*) - COUNT(ACCOUNT_ID)) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.MONTHLY_AMB;

-- Distinct Count Validation: MONTHLY_AMB.ACCOUNT_ID
-- Expected source distinct count: 1980
SELECT
    'MONTHLY_AMB.ACCOUNT_ID' AS VALIDATION_TARGET,
    COUNT(DISTINCT ACCOUNT_ID) AS TARGET_DISTINCT,
    1980 AS SOURCE_DISTINCT,
    CASE
        WHEN COUNT(DISTINCT ACCOUNT_ID) = 1980 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.MONTHLY_AMB;

-- Null Count Validation: MONTHLY_AMB.REPORTING_MONTH_YYYYMM
-- Expected source null count: 0
SELECT
    'MONTHLY_AMB.REPORTING_MONTH_YYYYMM' AS VALIDATION_TARGET,
    COUNT(*) - COUNT(REPORTING_MONTH_YYYYMM) AS TARGET_NULL_COUNT,
    0 AS SOURCE_NULL_COUNT,
    CASE
        WHEN (COUNT(*) - COUNT(REPORTING_MONTH_YYYYMM)) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.MONTHLY_AMB;

-- Distinct Count Validation: MONTHLY_AMB.REPORTING_MONTH_YYYYMM
-- Expected source distinct count: 1
SELECT
    'MONTHLY_AMB.REPORTING_MONTH_YYYYMM' AS VALIDATION_TARGET,
    COUNT(DISTINCT REPORTING_MONTH_YYYYMM) AS TARGET_DISTINCT,
    1 AS SOURCE_DISTINCT,
    CASE
        WHEN COUNT(DISTINCT REPORTING_MONTH_YYYYMM) = 1 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.MONTHLY_AMB;

-- Column Sum Validation: MONTHLY_AMB.REPORTING_MONTH_YYYYMM
-- Expected source sum: 400963860.0
SELECT
    'MONTHLY_AMB.REPORTING_MONTH_YYYYMM' AS VALIDATION_TARGET,
    SUM(REPORTING_MONTH_YYYYMM) AS TARGET_SUM,
    400963860.0 AS SOURCE_SUM,
    ABS(SUM(REPORTING_MONTH_YYYYMM) - 400963860.0) AS ABSOLUTE_DIFF,
    CASE
        WHEN ABS(SUM(REPORTING_MONTH_YYYYMM) - 400963860.0) < 0.01 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.MONTHLY_AMB;

-- Min/Max Validation: MONTHLY_AMB.REPORTING_MONTH_YYYYMM
-- Expected: MIN=202507, MAX=202507
SELECT
    'MONTHLY_AMB.REPORTING_MONTH_YYYYMM' AS VALIDATION_TARGET,
    MIN(REPORTING_MONTH_YYYYMM) AS TARGET_MIN,
    MAX(REPORTING_MONTH_YYYYMM) AS TARGET_MAX,
    202507 AS SOURCE_MIN,
    202507 AS SOURCE_MAX,
    CASE
        WHEN MIN(REPORTING_MONTH_YYYYMM) = 202507
         AND MAX(REPORTING_MONTH_YYYYMM) = 202507 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.MONTHLY_AMB;

-- Null Count Validation: MONTHLY_AMB.AVERAGE_MONTHLY_BALANCE
-- Expected source null count: 0
SELECT
    'MONTHLY_AMB.AVERAGE_MONTHLY_BALANCE' AS VALIDATION_TARGET,
    COUNT(*) - COUNT(AVERAGE_MONTHLY_BALANCE) AS TARGET_NULL_COUNT,
    0 AS SOURCE_NULL_COUNT,
    CASE
        WHEN (COUNT(*) - COUNT(AVERAGE_MONTHLY_BALANCE)) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.MONTHLY_AMB;

-- Distinct Count Validation: MONTHLY_AMB.AVERAGE_MONTHLY_BALANCE
-- Expected source distinct count: 1977
SELECT
    'MONTHLY_AMB.AVERAGE_MONTHLY_BALANCE' AS VALIDATION_TARGET,
    COUNT(DISTINCT AVERAGE_MONTHLY_BALANCE) AS TARGET_DISTINCT,
    1977 AS SOURCE_DISTINCT,
    CASE
        WHEN COUNT(DISTINCT AVERAGE_MONTHLY_BALANCE) = 1977 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.MONTHLY_AMB;

-- Column Sum Validation: MONTHLY_AMB.AVERAGE_MONTHLY_BALANCE
-- Expected source sum: 5702328.99
SELECT
    'MONTHLY_AMB.AVERAGE_MONTHLY_BALANCE' AS VALIDATION_TARGET,
    SUM(AVERAGE_MONTHLY_BALANCE) AS TARGET_SUM,
    5702328.99 AS SOURCE_SUM,
    ABS(SUM(AVERAGE_MONTHLY_BALANCE) - 5702328.99) AS ABSOLUTE_DIFF,
    CASE
        WHEN ABS(SUM(AVERAGE_MONTHLY_BALANCE) - 5702328.99) < 0.01 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.MONTHLY_AMB;

-- Min/Max Validation: MONTHLY_AMB.AVERAGE_MONTHLY_BALANCE
-- Expected: MIN=136.96, MAX=7675.76
SELECT
    'MONTHLY_AMB.AVERAGE_MONTHLY_BALANCE' AS VALIDATION_TARGET,
    MIN(AVERAGE_MONTHLY_BALANCE) AS TARGET_MIN,
    MAX(AVERAGE_MONTHLY_BALANCE) AS TARGET_MAX,
    136.96 AS SOURCE_MIN,
    7675.76 AS SOURCE_MAX,
    CASE
        WHEN MIN(AVERAGE_MONTHLY_BALANCE) = 136.96
         AND MAX(AVERAGE_MONTHLY_BALANCE) = 7675.76 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.MONTHLY_AMB;

-- Null Count Validation: MONTHLY_AMB.DATE_COMPUTED
-- Expected source null count: 0
SELECT
    'MONTHLY_AMB.DATE_COMPUTED' AS VALIDATION_TARGET,
    COUNT(*) - COUNT(DATE_COMPUTED) AS TARGET_NULL_COUNT,
    0 AS SOURCE_NULL_COUNT,
    CASE
        WHEN (COUNT(*) - COUNT(DATE_COMPUTED)) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.MONTHLY_AMB;

-- Distinct Count Validation: MONTHLY_AMB.DATE_COMPUTED
-- Expected source distinct count: 1
SELECT
    'MONTHLY_AMB.DATE_COMPUTED' AS VALIDATION_TARGET,
    COUNT(DISTINCT DATE_COMPUTED) AS TARGET_DISTINCT,
    1 AS SOURCE_DISTINCT,
    CASE
        WHEN COUNT(DISTINCT DATE_COMPUTED) = 1 THEN 'PASS'
        ELSE 'FAIL'
    END AS VALIDATION_RESULT
FROM SAS_MIGRATION_DB.BANKING.MONTHLY_AMB;

-- Hash-based Row Validation: MONTHLY_AMB
-- Compares MD5 hash of concatenated columns for sample rows
SELECT
    CUSTOMER_ID, ACCOUNT_ID, REPORTING_MONTH_YYYYMM,
    MD5(CONCAT_WS('|', CUSTOMER_ID, ACCOUNT_ID, REPORTING_MONTH_YYYYMM, AVERAGE_MONTHLY_BALANCE, DATE_COMPUTED)) AS ROW_HASH
FROM SAS_MIGRATION_DB.BANKING.MONTHLY_AMB
ORDER BY CUSTOMER_ID, ACCOUNT_ID, REPORTING_MONTH_YYYYMM
LIMIT 100;

-- Full Reconciliation Report
SELECT
    TABLE_NAME,
    VALIDATION_TYPE,
    VALIDATION_TARGET,
    SOURCE_VALUE,
    TARGET_VALUE,
    VALIDATION_RESULT
FROM (
    -- CUST_ACCOUNTS row count
    SELECT 'CUST_ACCOUNTS' AS TABLE_NAME, 'ROW_COUNT' AS VALIDATION_TYPE,
           'CUST_ACCOUNTS' AS VALIDATION_TARGET,
           '1980'::VARCHAR AS SOURCE_VALUE,
           COUNT(*)::VARCHAR AS TARGET_VALUE,
           CASE WHEN COUNT(*) = 1980 THEN 'PASS' ELSE 'FAIL' END AS VALIDATION_RESULT
    FROM SAS_MIGRATION_DB.BANKING.CUST_ACCOUNTS
    UNION ALL
    -- DAILY_BALANCE row count
    SELECT 'DAILY_BALANCE', 'ROW_COUNT', 'DAILY_BALANCE',
           '122760'::VARCHAR,
           COUNT(*)::VARCHAR,
           CASE WHEN COUNT(*) = 122760 THEN 'PASS' ELSE 'FAIL' END
    FROM SAS_MIGRATION_DB.BANKING.DAILY_BALANCE
    UNION ALL
    -- MONTHLY_AMB row count
    SELECT 'MONTHLY_AMB', 'ROW_COUNT', 'MONTHLY_AMB',
           '1980'::VARCHAR,
           COUNT(*)::VARCHAR,
           CASE WHEN COUNT(*) = 1980 THEN 'PASS' ELSE 'FAIL' END
    FROM SAS_MIGRATION_DB.BANKING.MONTHLY_AMB
    UNION ALL
    -- DAILY_BALANCE sum check
    SELECT 'DAILY_BALANCE', 'COLUMN_SUM', 'END_OF_DAY_BALANCE',
           '348911298.86'::VARCHAR,
           SUM(END_OF_DAY_BALANCE)::VARCHAR,
           CASE WHEN ABS(SUM(END_OF_DAY_BALANCE) - 348911298.86) < 0.01
                THEN 'PASS' ELSE 'FAIL' END
    FROM SAS_MIGRATION_DB.BANKING.DAILY_BALANCE
    UNION ALL
    -- MONTHLY_AMB sum check
    SELECT 'MONTHLY_AMB', 'COLUMN_SUM', 'AVERAGE_MONTHLY_BALANCE',
           '5702328.99'::VARCHAR,
           SUM(AVERAGE_MONTHLY_BALANCE)::VARCHAR,
           CASE WHEN ABS(SUM(AVERAGE_MONTHLY_BALANCE) - 5702328.99) < 0.01
                THEN 'PASS' ELSE 'FAIL' END
    FROM SAS_MIGRATION_DB.BANKING.MONTHLY_AMB
)
ORDER BY TABLE_NAME, VALIDATION_TYPE;
